In [1]:
import importlib
import scipy.sparse as sparse
import numpy as np
import hamiltonian as hm
import quantum as qm

In [2]:
importlib.reload(qm)

<module 'quantum' from '/Users/cstahl/Documents/Senior/Thesis/python/Hamiltonian/quantum.py'>

In [3]:
def check(a,b):
    print(np.all(np.isclose(a,b)))

In [4]:
L = 4
sx   = sparse.csr_matrix([[0., 1.],[1., 0.]]) 
test = sparse.csr_matrix([[1., 2.],[3j, 4.]]) 
test_large_dense = np.reshape(np.arange(2**(2*L)), (2**L,2**L))
test_large_sparse = sparse.csr_matrix(test_large_dense)

In [5]:
check(qm.mat_norm(test_large_sparse), hm.norm(test_large_dense))
site=1
check(hm.par_tr(test_large_dense, site), qm.par_tr(test_large_sparse, site).A)
check(hm.front_trace(test_large_dense, 2), qm.front_trace(test_large_sparse, 2).A)
check(hm.end_trace(test_large_dense, 2), qm.end_trace(test_large_sparse, 2).A)
check(qm.get_local_field([sx,sx,sx], [1,2,3]).A, 6*sx.A)

True
True
True
True
True


In [6]:
type([sx,sx])

list

In [7]:
mats = [a*b for a,b in zip([sx,sx,sx], [1,2,3])]
for item in mats: print(item.A)

[[ 0.  1.]
 [ 1.  0.]]
[[ 0.  2.]
 [ 2.  0.]]
[[ 0.  3.]
 [ 3.  0.]]


In [11]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5], [6]])
C = np.array([[7]])
mats = (A,B,C)
mats = (list(map(sparse.csr_matrix, mats)))
sparse.block_diag(mats).toarray()

array([[1, 2, 0, 0],
       [3, 4, 0, 0],
       [0, 0, 5, 0],
       [0, 0, 6, 0],
       [0, 0, 0, 7]], dtype=int64)

In [ ]:
list