In [1]:
import numpy as np

In [6]:
two_max = np.array([[-2, 2, 1, 0, 0, 0],
                    [ 1,-4, 1, 1, 0, 0],
                    [ 1, 1,-4, 1, 1, 0],
                    [ 0, 1, 1,-4, 1, 1],
                    [ 0, 0, 1, 1,-3, 1],
                    [ 0, 0, 0, 1, 1,-2]])
np.linalg.eig(two_max)

(array([  4.44089210e-16,  -1.12397007e+00,  -3.09350989e+00,
         -4.00000000e+00,  -5.52452410e+00,  -5.25799594e+00]),
 array([[ -5.33211430e-01,  -6.87818791e-01,   4.91216724e-01,
           5.00000000e-01,   3.66281546e-01,  -1.05947263e-01],
        [ -3.29512682e-01,  -2.28241868e-01,  -1.04451975e-01,
          -5.00000000e-01,  -4.76100772e-01,  -2.31031449e-01],
        [ -4.07397497e-01,  -1.46066112e-01,  -3.28246398e-01,
          -1.10266973e-15,  -3.38766591e-01,   8.07238651e-01],
        [ -3.77441799e-01,   1.77454458e-01,  -2.57655008e-01,
          -5.00000000e-01,   6.98312144e-01,  -4.10654762e-01],
        [ -3.89424078e-01,   3.18515690e-01,  -4.26661854e-01,
           5.00000000e-01,  -7.20350870e-02,  -2.67869474e-01],
        [ -3.83432939e-01,   5.66156623e-01,   6.25798511e-01,
           1.42550931e-15,  -1.77691240e-01,   2.08264298e-01]]))

In [7]:
two_max = np.array([[-2, 2, 1, 0, 0, 0, 0],
                    [ 1,-4, 1, 1, 0, 0, 0],
                    [ 1, 1,-4, 1, 1, 0, 0],
                    [ 0, 1, 1,-4, 1, 1, 0],
                    [ 0, 0, 1, 1,-4, 1, 1],
                    [ 0, 0, 0, 1, 1,-3, 1],
                    [ 0, 0, 0, 0, 1, 1,-2]])
np.linalg.eig(two_max)

(array([ -1.11022302e-16,  -8.65274774e-01,  -2.65251110e+00,
         -3.80898905e+00,  -4.49144693e+00,  -5.49625805e+00,
         -5.68552010e+00]),
 array([[-0.49718838, -0.65809628, -0.53466175, -0.4207886 , -0.3934465 ,
          0.26005375, -0.30829571],
        [-0.30727522, -0.26695596,  0.08935505,  0.20241974,  0.62433982,
         -0.13836806,  0.55064507],
        [-0.37982631, -0.21284653,  0.17016263,  0.35636247, -0.26842857,
         -0.6324789 ,  0.03493988],
        [-0.35208619,  0.03410923,  0.48490405,  0.10309051,  0.35504518,
          0.57945947, -0.65476751],
        [-0.36275547,  0.22372762,  0.18969491,  0.18334748, -0.45402011,
          0.24520648,  0.35352627],
        [-0.35848776,  0.36299793,  0.20419023, -0.72243828, -0.07637701,
         -0.34138043,  0.16451257],
        [-0.36062161,  0.51706399, -0.60364512,  0.29800667,  0.21288718,
          0.02750768, -0.14056058]]))

In [ ]:
two_max = np.array([[-2, 2, 1, 0, 0, 0, 0],
                    [ 1,-4, 1, 1, 0, 0, 0],
                    [ 1, 1,-4, 1, 1, 0, 0],
                    [ 0, 1, 1,-4, 1, 1, 0],
                    [ 0, 0, 1, 1,-4, 1, 1],
                    [ 0, 0, 0, 1, 1,-3, 1],
                    [ 0, 0, 0, 0, 1, 1,-2]])
np.linalg.eig(two_max)